### ISSUE TITLE
Start tunnel in nexjts `instrumentation.ts` will encounter a RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by shiny** [JacobLinCool/node-cloudflared#30]
I placed the example code into `instrumentation.ts`
```ts
import { Tunnel } from "cloudflared";

console.log("Cloudflared Tunnel Example.");
main();

async function main() {
  // run: cloudflared tunnel --hello-world
  const tunnel = Tunnel.quick();

  // show the url
  const url = new Promise((resolve) => tunnel.once("url", resolve));
  console.log("LINK:", await url);

  // wait for connection to be established
  const conn = new Promise((resolve) => tunnel.once("connected", resolve));
  console.log("CONN:", await conn);

  // stop the tunnel after 15 seconds
  setTimeout(tunnel.stop, 15_000);

  tunnel.on("exit", (code) => {
    console.log("tunnel process exited with code", code);
  });
}
```

Encounter an error below

$ next dev --turbopack
   ▲ Next.js 15.0.3 (Turbopack)
   - Local:        http://localhost:3000
   - Environments: .env.local, .env
   - Experiments (use with caution):
     · turbo

 ✓ Starting...
 ✓ Compiled in 283ms
Cloudflared Tunnel Example.
RangeError: Maximum call stack size exceeded
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
    at Tunnel.<anonymous> (node_modules/cloudflared/lib/tunnel.js:78:11)
    at Tunnel.emit (node_modules/cloudflared/lib/tunnel.js:112:17)
  110 |   }
  111 |   emit(event, ...args) {
> 112 |     return super.emit(event, ...args);
      |                 ^
  113 |   }
  114 |   /**
  115 |    * Create a quick tunnel without a Cloudflare account.
 ✓ Ready in 989ms
^C

**Comment by rhyek** [comment]
What was the issue/fix?
